// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go-microservice-tutorial/organization-api/sdk/models"
)

// UpdateTenantReader is a Reader for the UpdateTenant structure.
type UpdateTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateTenantCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUpdateTenantNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateTenantUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateTenantCreated creates a UpdateTenantCreated with default headers values
func NewUpdateTenantCreated() *UpdateTenantCreated {
	return &UpdateTenantCreated{}
}

/*UpdateTenantCreated handles this case with default header values.

No content is returned by this API endpoint
*/
type UpdateTenantCreated struct {
}

func (o *UpdateTenantCreated) Error() string {
	return fmt.Sprintf("[PUT /tenants][%d] updateTenantCreated ", 201)
}

func (o *UpdateTenantCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateTenantNotFound creates a UpdateTenantNotFound with default headers values
func NewUpdateTenantNotFound() *UpdateTenantNotFound {
	return &UpdateTenantNotFound{}
}

/*UpdateTenantNotFound handles this case with default header values.

Generic error message returned as a string
*/
type UpdateTenantNotFound struct {
	Payload *models.GenericError
}

func (o *UpdateTenantNotFound) Error() string {
	return fmt.Sprintf("[PUT /tenants][%d] updateTenantNotFound  %+v", 404, o.Payload)
}

func (o *UpdateTenantNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateTenantNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTenantUnprocessableEntity creates a UpdateTenantUnprocessableEntity with default headers values
func NewUpdateTenantUnprocessableEntity() *UpdateTenantUnprocessableEntity {
	return &UpdateTenantUnprocessableEntity{}
}

/*UpdateTenantUnprocessableEntity handles this case with default header values.

Validation errors defined as an array of strings
*/
type UpdateTenantUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *UpdateTenantUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /tenants][%d] updateTenantUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *UpdateTenantUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *UpdateTenantUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
